sudo: required
language: generic
services:
  - docker

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - docker build -t hareramrai/rails_ecr_sample_app -f ./docker/app/Dockerfile .
  - docker build -t hareramrai/rails_ecr_sample_web -f ./docker/web/Dockerfile .

script:
  - docker run -e RAILS_ENV=test rails_ecr_sample_app rspec

after_success:

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker build -t hareramrai/rails_ecr_sample_app -f ./docker/app/Dockerfile .
  - docker push hareramrai/rails_ecr_sample_app

  - docker build -t hareramrai/rails_ecr_sample_web -f ./docker/web/Dockerfile .
  - docker push hareramrai/rails_ecr_sample_web

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: rails_ecr_sample_app
  env: RailsEcrSampleApp-env
  bucket_name: elasticbeanstalk-us-east-1-525597256582
  bucket_path: rails_ecr_app
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"